apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: dummy-app-svc-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 5s
    targetPort: 9000
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      svcname: dummy-app